#!/usr/bin/env ruby
# frozen_string_literal: true

# vim: filetype=ruby

lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

class Nyanco
  def needName
    puts ''
    require 'nagakutu/version'
    puts 'ゆきねこのばーじょん : ' + Neko::VERSION
  end

  def yuki
    require 'snow'
  end
end

puts ''
puts 'version'.center(70, '-')
Nyanco.new.needName
puts ''
puts 'version'.center(70, '-')
puts ''
puts 'encrypt'.center(70, '-')
Nyanco.new.yuki
puts ''
puts 'encrypt'.center(70, '-')
puts ''